name: camdell
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  extended_image: ^8.2.4
  flutter_svg: ^2.0.10+1
  # google_maps_flutter: ^2.9.0
  flutter_staggered_grid_view: ^0.7.0
  dio: ^5.7.0
  flutter_map: ^7.0.2
  font_awesome_flutter: ^10.7.0
  geolocator: ^13.0.1
  dotted_border: ^2.1.0
  ripple_wave: ^0.1.4
  counter_button: ^1.0.1
  flutter_circular_progress_indicator: ^0.0.3
  change_app_package_name: ^1.4.0
  firebase_core: ^3.6.0
  email_auth: ^2.0.0
  cloud_functions: ^5.1.3
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_facebook_auth: ^6.0.4
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.2
  firebase_dynamic_links: ^6.0.8
  twilio_flutter: ^0.9.0
  shared_preferences: ^2.3.2
  local_auth: ^2.3.0
  country_picker: ^2.0.26
  country_code_picker: ^3.1.0

  # auto_size_text: ^3.0.0
  # extended_image: ^8.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter_gen:
  line_length: 120
  integrations:
    flutter_svg: true
    lottie: true
flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/icons/
    - assets/images/nav/
    - assets/images/fruits/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
