// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXWI9P97AhbocrvetgV4LyCFa6JEWUkyM',
    appId: '1:157748106197:web:caa5103e9861b7dca8635c',
    messagingSenderId: '157748106197',
    projectId: 'camdell-app',
    authDomain: 'camdell-app.firebaseapp.com',
    storageBucket: 'camdell-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApAdBIGjmpjJ_xCWVl9ys1O-47G3GJpvk',
    appId: '1:157748106197:android:efb65027973b8d15a8635c',
    messagingSenderId: '157748106197',
    projectId: 'camdell-app',
    storageBucket: 'camdell-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0E4JTY-7npGlNRKfO25jHxtYBx_u2Wbg',
    appId: '1:157748106197:ios:472b66a167dd8972a8635c',
    messagingSenderId: '157748106197',
    projectId: 'camdell-app',
    storageBucket: 'camdell-app.appspot.com',
    iosBundleId: 'com.camdell.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0E4JTY-7npGlNRKfO25jHxtYBx_u2Wbg',
    appId: '1:157748106197:ios:4d841d54df517bd8a8635c',
    messagingSenderId: '157748106197',
    projectId: 'camdell-app',
    storageBucket: 'camdell-app.appspot.com',
    iosBundleId: 'com.example.camdell.RunnerTests',
  );
}
